export const SEND_TO_EMAIL_REQUEST = "SEND_TO_EMAIL_REQUEST";
export const SEND_TO_EMAIL_SUCCESS = "SEND_TO_EMAIL_SUCCESS";
export const SEND_TO_EMAIL_FAILURE = "SEND_TO_EMAIL_FAILURE";

export const AUTH_OTP_REQUEST = "AUTH_OTP_REQUEST";
export const AUTH_OTP_SUCCESS = "AUTH_OTP_SUCCESS";
export const AUTH_OTP_FAILURE = "AUTH_OTP_FAILURE";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";
